### ISSUE TITLE
All of a sudden DCO App not running in any repos in org

### ISSUE THREAD

**Issue by mynameistechno** [probot/dco#168] opened 2021-10-12 15:41 UTC
In our org the DCO check stopped running on PRs. Others in different orgs have reported similar issues "DCO—  Waiting for status to be reported"

**Comment by hiimbex** [comment] 2021-10-13 00:51
duplicate of https://github.com/probot/dco/issues/162

**Closed by hiimbex** 2021-10-13 00:51 UTC
