### ISSUE TITLE
Read sign-offs in PR comments

### ISSUE THREAD

**Issue by itayd** [probot/dco#105] opened 2019-01-25 23:30 UTC
(This is an alternative suggestion for https://github.com/probot/dco/issues/74)

To my understanding, the legal requirement is that each commit must be signed to prove that the authors themselves signed these off, and that's the only authenticated way to do so. I am wondering if a GitHub comment that is from the commit author could fulfill the same requirement? That way a simpler way for signing off contributions could be implemented.

In essence, a committer would comment something like "/dco-approve" and it'll make the bot consider all previous commits as signed off.

This functionality will be enabled by a config file field.

Would be happy to implement this if this makes sense.

**Comment by hiimbex** [comment] 2019-03-03 22:37
I'm not a lawyer and don't really use the DCO on my projects so I'm fine with this. I think enabling via conifg option (which is by default disabled) should satisfy those from the Linux Foundation who have lawyers decide these things.

PRs welcome!

**Comment by hiimbex** [comment] 2019-03-03 22:40
Also duplicate of https://github.com/probot/dco/issues/83

**Closed** 2019-07-01 23:32 UTC
Labels: wontfix
