### ISSUE TITLE
DCO bot is stuck in "waiting for status reported"

### ISSUE THREAD

**Issue by caniszczyk** [probot/dco#69] opened 2018-04-23 19:31 UTC
https://github.com/envoyproxy/envoy/pull/3021

Any idea what's up?

**Comment by bkeepers** [comment] 2018-04-23 19:41
Looks like #67 might have introduced a bug? cc @hiimbex 

```
19:23:09.173Z ERROR event: isRequiredFor is not a function (id=c0269540-472b-11e8-9a34-0be6bd8fd8f7)
  TypeError: isRequiredFor is not a function
      at module.exports (/app/lib/dco.js:17:35)
      at check (/app/index.js:22:29)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:182:7)
  --
  event: {
    "id": "c0269540-472b-11e8-9a34-0be6bd8fd8f7",
    "event": "pull_request.synchronize",
    "repository": "envoyproxy/envoy",
    "installation": 53244
  }
```

**Comment by jwagantall** [comment] 2018-05-07 22:50
Hi all, 

Can someone please help me checking if something is causing this delay again?
Looks like my PR has gone stuck "waiting for status to be reported":
https://github.com/hyperledger-labs/private-data-objects/pull/5

Thank you so much!
Jess

**Comment by dcmiddle** [comment] 2018-05-08 12:52
This one was stuck and we ended up closing it and opening it as a new item to get past DCO being stuck. https://github.com/hyperledger/sawtooth-core/pull/1572

**Comment by dcmiddle** [comment] 2018-05-14 16:32
another PR stuck on DCO: https://github.com/hyperledger/sawtooth-core/pull/1554

**Comment by JPWKU** [comment] 2018-05-17 16:54
Hi, We are still seeing this issue.  https://github.com/edgexfoundry/blackbox-testing/pull/24

**Comment by hiimbex** [comment] 2018-05-18 19:02
Sorry for the delay and thanks for your patience with this issue.

I think we resolved some of the causes of the "hanging" in #72, but for older PRs the DCO might need to be re-triggered to run on the PR. Opening new PRs to re-trigger the bot is definitely the first step. And I think for the PRs opened more than a week or two ago, future PRs should be fine.

The only PR here that doesn't fit that criterion is @JPWKU issue, which I think may have been due to the first commit having `Signed-off-by: Bruce <weichou1229@gmail.com>` and the rest of the commits having `Signed-off-by: Bruce <bruce@angel-tech.com.tw>` as well as the changing of the git user throughout the commits. Still, I wouldn't expect the bot to "hang" in this situation, so I'll be looking into it further.

**Comment by hiimbex** [comment] 2018-05-18 19:03
Sorry for the delay and thanks for your patience with this issue.

I think we resolved some of the causes of the "hanging" in #72, but for older PRs the DCO might need to be re-triggered to run on the PR. Opening new PRs to re-trigger the bot is definitely the first step. And I think for the PRs opened more than a week or two ago, future PRs should be fine.

The only PR here that doesn't fit that criterion is @JPWKU issue, which I think may have been due to the first commit having `Signed-off-by: Bruce <weichou1229@gmail.com>` and the rest of the commits having `Signed-off-by: Bruce <bruce@angel-tech.com.tw>` as well as the changing of the git user throughout the commits. Still, I wouldn't expect the bot to "hang" in this situation, so I'll be looking into it further.

**Comment by JPWKU** [comment] 2018-05-18 19:08
Hi @hiimbex , That indeed was the issue.  weichou1229 closed the old PR and resigned the commits with  the same git  user and resubmitting.  It checked out after that.  Thanks for looking into it.

**Comment by JPWKU** [comment] 2018-05-18 19:09
@hiimbex I agree that it seemed a weird case for it to hang though.

**Comment by hiimbex** [comment] 2018-05-25 21:08
This is definitely the exact same issue @JPWKU just described, so I'd recommend that Mic Bowman (the original committer) associate his github account with those commits by editing his [GitHub global configs locally](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration) and recommitting.

If this is a new contributor though, doing all of that git meddling might be confusing in which case I'd recommend just copying the changes and making a new commit once their global git config is set up.

Also you can remove DCO as a 'required' check in the settings page. But that does need to be done by someone with admin permissions.

I am looking into this issue and hope to have a solution soon, since this is obviously not our intended behavior.

**Comment by hiimbex** [comment] 2018-05-25 21:45
See: #77 for the solution to this issue.

**Closed** 2018-07-02 20:11 UTC

**Comment by brianjmurrell** [comment] 2019-03-29 15:41
This still happens.  See [this PR](https://github.com/daos-stack/daos/pull/227) for an example.

Please advise ASAP as I cannot ask this user to leave this PR in this state for long.  He needs to move on and get the PR landed.
